### ISSUE TITLE
When will the library be compatible with SquareMobilePaymentsSDK version 2.2.1?

### ISSUE THREAD

**Issue by jimc-jpgreze** [square/mobile-payments-sdk-react-native#47]
While I have been able to get the library to build with the v2.1.0 of SquareMobilePaymentsSDK, I need to work with v2.2.1, as there is a patch in this version for iOS 18.4 that prevents crashes on certain iPads. I tried to upgrade to SquareMobilePaymentsSDK to v2.2.1, but when I try to build, I get this error:

```
/Users/jimc/Workspaces/funfangle-mobile-pos-rn/node_modules/mobile-payments-sdk-react-native/ios/Mappers.swift:37:103: error: missing argument for parameter 'processingMode' in call
        let paymentParams = PaymentParameters(idempotencyKey: idempotencyKey, amountMoney: amountMoney)
                                                                                                      ^
                                                                                                      , processingMode: <#ProcessingMode#>
SquareMobilePaymentsSDK.PaymentParameters:21:12: note: 'init(idempotencyKey:amountMoney:processingMode:)' declared here
    public init(idempotencyKey: String, amountMoney: any MoneyAmount, processingMode: ProcessingMode)
           ^
```

Clearly something has changed. When will the react-native code be updated to support v2.2.1? Is there some workaround I can use to get past this?

Thanks,
Jim

**Comment by fobos531** [comment]
@jimc-jpgreze As a quick workaround you can simply use patch package, and set the processing mode manually, so, like this:

```        
let paymentParams = PaymentParameters(idempotencyKey: idempotencyKey, amountMoney: amountMoney, processingMode: .onlineOnly)
```

I set it above to onlineOnly, but you can use other available options
